// <auto-generated />
using System;
using EAMS.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EAMS.Infrastructure.Migrations
{
    [DbContext(typeof(EamsDbContext))]
    [Migration("20260729070621_AttendanceRowVersionCursor")]
    partial class AttendanceRowVersionCursor
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("EAMS.Domain.AcademicProgram", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("CollegeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId")
                        .HasDatabaseName("IX_Programs_CollegeId");

                    b.HasIndex("SchoolId", "CodeKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Programs_SchoolId_CodeKey");

                    b.ToTable("Programs", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.AttendanceRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CaptureMethod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Rfid");

                    b.Property<DateTime?>("CheckInAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("CheckOutAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CheckOutDeviceTapId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DeviceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DeviceTapId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Notes")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<Guid?>("OccurrenceId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RecordedByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("RfidCardId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("RowVersion")
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeviceId");

                    b.HasIndex("OccurrenceId");

                    b.HasIndex("RecordedByUserId");

                    b.HasIndex("RfidCardId");

                    b.HasIndex("StudentId");

                    b.HasIndex("EventId", "RowVersion")
                        .HasDatabaseName("IX_Attendance_EventId_RowVersion");

                    b.HasIndex("EventId", "Status")
                        .HasDatabaseName("IX_Attendance_EventId_Status");

                    b.HasIndex("EventId", "StudentId", "OccurrenceId")
                        .IsUnique()
                        .HasDatabaseName("UX_Attendance_Event_Student_Occurrence");

                    b.HasIndex("SchoolId", "DeviceId", "CheckOutDeviceTapId")
                        .IsUnique()
                        .HasDatabaseName("UX_Attendance_Device_CheckOutDeviceTapId")
                        .HasFilter("[CheckOutDeviceTapId] IS NOT NULL");

                    b.HasIndex("SchoolId", "DeviceId", "DeviceTapId")
                        .IsUnique()
                        .HasDatabaseName("UX_Attendance_Device_DeviceTapId")
                        .HasFilter("[DeviceTapId] IS NOT NULL");

                    b.ToTable("AttendanceRecords", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.AuditLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Changes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IpAddress")
                        .HasMaxLength(45)
                        .HasColumnType("nvarchar(45)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt")
                        .HasDatabaseName("IX_AuditLogs_CreatedAt");

                    b.HasIndex("UserId");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_AuditLogs_Entity");

                    b.ToTable("AuditLogs", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.College", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "NameKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Colleges_SchoolId_NameKey");

                    b.ToTable("Colleges", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.Course", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("CodeKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("CollegeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Title")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.HasIndex("SchoolId", "CodeKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Courses_SchoolId_CodeKey");

                    b.ToTable("Courses", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.CourseOffering", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("SectionKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("(unspecified)");

                    b.Property<string>("SectionName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.HasIndex("TermId", "SectionKey")
                        .HasDatabaseName("IX_CourseOfferings_TermId_SectionKey");

                    b.HasIndex("TermId", "CourseId", "SectionKey")
                        .IsUnique()
                        .HasDatabaseName("UX_CourseOfferings_Term_Course_Section");

                    b.ToTable("CourseOfferings", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.CourseOfferingInstructor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("InstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("InstructorId");

                    b.HasIndex("CourseOfferingId", "InstructorId")
                        .IsUnique()
                        .HasDatabaseName("UX_CourseOfferingInstructors_Offering_Instructor");

                    b.ToTable("CourseOfferingInstructors", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.Device", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ApiKey")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("ApiKeyHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("ApiKeyId")
                        .HasMaxLength(12)
                        .HasColumnType("nvarchar(12)");

                    b.Property<DateTime?>("ApiKeyIssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ApiKeyLastUsedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ApiKeyRevokedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeviceType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastSeenAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ReaderModel")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ApiKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Devices_ApiKey")
                        .HasFilter("[ApiKey] IS NOT NULL");

                    b.HasIndex("ApiKeyId")
                        .IsUnique()
                        .HasDatabaseName("UX_Devices_ApiKeyId")
                        .HasFilter("[ApiKeyId] IS NOT NULL");

                    b.HasIndex("SchoolId");

                    b.ToTable("Devices", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.Enrollment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("CourseOfferingId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CourseOfferingId")
                        .HasDatabaseName("IX_Enrollments_CourseOfferingId");

                    b.HasIndex("StudentId", "CourseOfferingId")
                        .IsUnique()
                        .HasDatabaseName("UX_Enrollments_Student_CourseOffering");

                    b.ToTable("Enrollments", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.Event", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AttendanceMode")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Single");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<DateTime>("EndAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("GraceMinutes")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Location")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid?>("OrganizerUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("RequireRegistration")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Draft");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("OrganizerUserId");

                    b.HasIndex("SchoolId");

                    b.ToTable("Events", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.EventGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StudentGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EventId")
                        .HasDatabaseName("IX_EventGroups_EventId");

                    b.HasIndex("StudentGroupId");

                    b.HasIndex("StudentId");

                    b.HasIndex("EventId", "StudentGroupId")
                        .IsUnique()
                        .HasDatabaseName("UX_EventGroups_Event_Group")
                        .HasFilter("[StudentGroupId] IS NOT NULL");

                    b.HasIndex("EventId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("UX_EventGroups_Event_Student")
                        .HasFilter("[StudentId] IS NOT NULL");

                    b.ToTable("EventGroups", null, t =>
                        {
                            t.HasCheckConstraint("CK_EventGroups_GroupOrStudent", "([StudentGroupId] IS NULL AND [StudentId] IS NOT NULL) OR ([StudentGroupId] IS NOT NULL AND [StudentId] IS NULL)");
                        });
                });

            modelBuilder.Entity("EAMS.Domain.EventSchedule", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsCancelled")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("OccurrenceEndAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("OccurrenceStartAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("RecurrenceRule")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.ToTable("EventSchedules", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.Instructor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("ExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("MergedIntoInstructorId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("MergedIntoInstructorId");

                    b.HasIndex("SchoolId", "ExternalId")
                        .IsUnique()
                        .HasDatabaseName("UX_Instructors_SchoolId_ExternalId")
                        .HasFilter("[ExternalId] IS NOT NULL");

                    b.HasIndex("SchoolId", "NameKey")
                        .IsUnique()
                        .HasDatabaseName("UX_Instructors_SchoolId_NameKey");

                    b.ToTable("Instructors", null, t =>
                        {
                            t.HasCheckConstraint("CK_Instructors_NoSelfMerge", "[MergedIntoInstructorId] IS NULL OR [MergedIntoInstructorId] <> [Id]");
                        });
                });

            modelBuilder.Entity("EAMS.Domain.Permission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Permissions_Code");

                    b.ToTable("Permissions", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.RfidCard", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CardUid")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("DeactivatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Label")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CardUid")
                        .HasDatabaseName("IX_RfidCards_CardUid");

                    b.HasIndex("StudentId");

                    b.HasIndex("SchoolId", "CardUid")
                        .IsUnique()
                        .HasDatabaseName("UX_RfidCards_SchoolId_CardUid_Active")
                        .HasFilter("[IsActive] = 1");

                    b.ToTable("RfidCards", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Description")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasDatabaseName("UX_Roles_Name");

                    b.ToTable("Roles", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.RolePermission", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PermissionId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("PermissionId");

                    b.HasIndex("RoleId", "PermissionId")
                        .IsUnique()
                        .HasDatabaseName("UX_RolePermissions_Role_Permission");

                    b.ToTable("RolePermissions", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.School", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Address")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TimeZone")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)")
                        .HasDefaultValue("Asia/Manila");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Schools", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.SisImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("FailedRows")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("FileHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("FileName")
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<DateTime?>("FinishedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("ImportProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("InsertedRows")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid?>("RunByUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("SkippedRows")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("SourceSheetName")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<DateTime?>("StartedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("TotalRows")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("UpdatedRows")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<int>("WarningRows")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.HasKey("Id");

                    b.HasIndex("ImportProfileId");

                    b.HasIndex("RunByUserId");

                    b.HasIndex("TermId");

                    b.HasIndex("SchoolId", "TermId")
                        .HasDatabaseName("IX_SisImportBatches_SchoolId_TermId");

                    b.ToTable("SisImportBatches", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.SisImportProfile", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("NameKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "NameKey")
                        .IsUnique()
                        .HasDatabaseName("UX_SisImportProfiles_School_Name_Active")
                        .HasFilter("[IsActive] = 1");

                    b.HasIndex("SchoolId", "NameKey", "Version")
                        .IsUnique()
                        .HasDatabaseName("UX_SisImportProfiles_School_Name_Version");

                    b.ToTable("SisImportProfiles", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.SisImportProfileColumn", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsRequired")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("NormalizationRule")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Ordinal")
                        .HasColumnType("int")
                        .HasDefaultValue(0);

                    b.Property<Guid>("ProfileId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceColumn")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("SourceColumnKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TargetField")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProfileId", "SourceColumnKey", "TargetField")
                        .IsUnique()
                        .HasDatabaseName("UX_SisImportProfileColumns_Profile_Column_Target");

                    b.ToTable("SisImportProfileColumns", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.SisImportRow", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("RawData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("RowHash")
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<int>("RowNumber")
                        .HasColumnType("int");

                    b.Property<string>("SkipReason")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<Guid?>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("WarningCode")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("WarningMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("BatchId", "Result")
                        .HasDatabaseName("IX_SisImportRows_BatchId_Result");

                    b.HasIndex("BatchId", "RowNumber")
                        .IsUnique()
                        .HasDatabaseName("UX_SisImportRows_Batch_RowNumber");

                    b.ToTable("SisImportRows", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.SisImportRowEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("EntityType")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.Property<Guid>("SisImportRowId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("EntityType", "EntityId")
                        .HasDatabaseName("IX_SisImportRowEntities_Entity");

                    b.HasIndex("SisImportRowId", "EntityType", "EntityId")
                        .IsUnique()
                        .HasDatabaseName("UX_SisImportRowEntities_Row_Type_Entity");

                    b.ToTable("SisImportRowEntities", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.Student", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime?>("AcademicCacheUpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("AlternateEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("Course")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Section")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SisExternalId")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Active");

                    b.Property<string>("StudentNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("YearLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("SisExternalId")
                        .HasDatabaseName("IX_Students_SisExternalId");

                    b.HasIndex("StudentNumber")
                        .HasDatabaseName("IX_Students_StudentNumber");

                    b.HasIndex("LastName", "FirstName")
                        .HasDatabaseName("IX_Students_LastName_FirstName");

                    b.HasIndex("SchoolId", "StudentNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Students_SchoolId_StudentNumber");

                    b.ToTable("Students", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.StudentGroup", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SourceEntityId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceEntityType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)")
                        .HasDefaultValue("None");

                    b.Property<string>("SourceKey")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)")
                        .HasDefaultValue("");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Manual");

                    b.Property<Guid?>("TermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId")
                        .HasDatabaseName("IX_StudentGroups_SchoolId");

                    b.HasIndex("TermId");

                    b.HasIndex("SchoolId", "TermId", "SourceEntityType", "SourceKey")
                        .IsUnique()
                        .HasDatabaseName("UX_StudentGroups_Derived_Source")
                        .HasFilter("[SourceType] = 'Derived'");

                    b.ToTable("StudentGroups", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.StudentGroupMember", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SourceType")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)")
                        .HasDefaultValue("Manual");

                    b.Property<Guid>("StudentGroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("StudentId");

                    b.HasIndex("StudentGroupId", "StudentId")
                        .IsUnique()
                        .HasDatabaseName("UX_StudentGroupMembers_Group_Student");

                    b.ToTable("StudentGroupMembers", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.StudentTermRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("CollegeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("HomeSectionKey")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("HomeSectionName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("ProgramId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("StudentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TermId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("YearLevel")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CollegeId");

                    b.HasIndex("ProgramId");

                    b.HasIndex("TermId")
                        .HasDatabaseName("IX_StudentTermRecords_TermId");

                    b.HasIndex("StudentId", "TermId")
                        .IsUnique()
                        .HasDatabaseName("UX_StudentTermRecords_Student_Term");

                    b.ToTable("StudentTermRecords", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.SystemSetting", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("DataType")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<Guid?>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId", "Key")
                        .IsUnique()
                        .HasDatabaseName("UX_SystemSettings_SchoolId_Key");

                    b.ToTable("SystemSettings", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.Term", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<DateOnly?>("EndsOn")
                        .HasColumnType("date");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit")
                        .HasDefaultValue(false);

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SchoolYear")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Semester")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<DateOnly?>("StartsOn")
                        .HasColumnType("date");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("SchoolId")
                        .IsUnique()
                        .HasDatabaseName("UX_Terms_SchoolId_Current")
                        .HasFilter("[IsCurrent] = 1");

                    b.HasIndex("SchoolId", "Code")
                        .IsUnique()
                        .HasDatabaseName("UX_Terms_SchoolId_Code");

                    b.ToTable("Terms", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.User", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit")
                        .HasDefaultValue(true);

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("RefreshTokenHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("SchoolId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("UX_Users_Email");

                    b.HasIndex("SchoolId");

                    b.ToTable("Users", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.UserRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.HasIndex("UserId", "RoleId")
                        .IsUnique()
                        .HasDatabaseName("UX_UserRoles_User_Role");

                    b.ToTable("UserRoles", (string)null);
                });

            modelBuilder.Entity("EAMS.Domain.AcademicProgram", b =>
                {
                    b.HasOne("EAMS.Domain.College", "College")
                        .WithMany("Programs")
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EAMS.Domain.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("College");

                    b.Navigation("School");
                });

            modelBuilder.Entity("EAMS.Domain.AttendanceRecord", b =>
                {
                    b.HasOne("EAMS.Domain.Device", "Device")
                        .WithMany()
                        .HasForeignKey("DeviceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EAMS.Domain.Event", "Event")
                        .WithMany("AttendanceRecords")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EAMS.Domain.EventSchedule", "Occurrence")
                        .WithMany()
                        .HasForeignKey("OccurrenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EAMS.Domain.User", "RecordedByUser")
                        .WithMany()
                        .HasForeignKey("RecordedByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EAMS.Domain.RfidCard", "RfidCard")
                        .WithMany()
                        .HasForeignKey("RfidCardId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EAMS.Domain.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EAMS.Domain.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Device");

                    b.Navigation("Event");

                    b.Navigation("Occurrence");

                    b.Navigation("RecordedByUser");

                    b.Navigation("RfidCard");

                    b.Navigation("School");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EAMS.Domain.AuditLog", b =>
                {
                    b.HasOne("EAMS.Domain.User", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("User");
                });

            modelBuilder.Entity("EAMS.Domain.College", b =>
                {
                    b.HasOne("EAMS.Domain.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("EAMS.Domain.Course", b =>
                {
                    b.HasOne("EAMS.Domain.College", "College")
                        .WithMany()
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EAMS.Domain.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("College");

                    b.Navigation("School");
                });

            modelBuilder.Entity("EAMS.Domain.CourseOffering", b =>
                {
                    b.HasOne("EAMS.Domain.Course", "Course")
                        .WithMany("Offerings")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EAMS.Domain.Term", "Term")
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Course");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("EAMS.Domain.CourseOfferingInstructor", b =>
                {
                    b.HasOne("EAMS.Domain.CourseOffering", "CourseOffering")
                        .WithMany("Instructors")
                        .HasForeignKey("CourseOfferingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EAMS.Domain.Instructor", "Instructor")
                        .WithMany()
                        .HasForeignKey("InstructorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseOffering");

                    b.Navigation("Instructor");
                });

            modelBuilder.Entity("EAMS.Domain.Device", b =>
                {
                    b.HasOne("EAMS.Domain.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("EAMS.Domain.Enrollment", b =>
                {
                    b.HasOne("EAMS.Domain.CourseOffering", "CourseOffering")
                        .WithMany("Enrollments")
                        .HasForeignKey("CourseOfferingId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EAMS.Domain.Student", "Student")
                        .WithMany("Enrollments")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CourseOffering");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EAMS.Domain.Event", b =>
                {
                    b.HasOne("EAMS.Domain.User", "OrganizerUser")
                        .WithMany()
                        .HasForeignKey("OrganizerUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EAMS.Domain.School", "School")
                        .WithMany("Events")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("OrganizerUser");

                    b.Navigation("School");
                });

            modelBuilder.Entity("EAMS.Domain.EventGroup", b =>
                {
                    b.HasOne("EAMS.Domain.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EAMS.Domain.StudentGroup", "StudentGroup")
                        .WithMany()
                        .HasForeignKey("StudentGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EAMS.Domain.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Event");

                    b.Navigation("Student");

                    b.Navigation("StudentGroup");
                });

            modelBuilder.Entity("EAMS.Domain.EventSchedule", b =>
                {
                    b.HasOne("EAMS.Domain.Event", "Event")
                        .WithMany("Schedules")
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Event");
                });

            modelBuilder.Entity("EAMS.Domain.Instructor", b =>
                {
                    b.HasOne("EAMS.Domain.Instructor", "MergedIntoInstructor")
                        .WithMany()
                        .HasForeignKey("MergedIntoInstructorId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EAMS.Domain.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("MergedIntoInstructor");

                    b.Navigation("School");
                });

            modelBuilder.Entity("EAMS.Domain.RfidCard", b =>
                {
                    b.HasOne("EAMS.Domain.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EAMS.Domain.Student", "Student")
                        .WithMany("Cards")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EAMS.Domain.RolePermission", b =>
                {
                    b.HasOne("EAMS.Domain.Permission", "Permission")
                        .WithMany("RolePermissions")
                        .HasForeignKey("PermissionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EAMS.Domain.Role", "Role")
                        .WithMany("RolePermissions")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Permission");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("EAMS.Domain.SisImportBatch", b =>
                {
                    b.HasOne("EAMS.Domain.SisImportProfile", "ImportProfile")
                        .WithMany()
                        .HasForeignKey("ImportProfileId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EAMS.Domain.User", "RunByUser")
                        .WithMany()
                        .HasForeignKey("RunByUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EAMS.Domain.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EAMS.Domain.Term", "Term")
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ImportProfile");

                    b.Navigation("RunByUser");

                    b.Navigation("School");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("EAMS.Domain.SisImportProfile", b =>
                {
                    b.HasOne("EAMS.Domain.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("EAMS.Domain.SisImportProfileColumn", b =>
                {
                    b.HasOne("EAMS.Domain.SisImportProfile", "Profile")
                        .WithMany("Columns")
                        .HasForeignKey("ProfileId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Profile");
                });

            modelBuilder.Entity("EAMS.Domain.SisImportRow", b =>
                {
                    b.HasOne("EAMS.Domain.SisImportBatch", "Batch")
                        .WithMany("Rows")
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EAMS.Domain.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Batch");

                    b.Navigation("Student");
                });

            modelBuilder.Entity("EAMS.Domain.SisImportRowEntity", b =>
                {
                    b.HasOne("EAMS.Domain.SisImportRow", "SisImportRow")
                        .WithMany("Entities")
                        .HasForeignKey("SisImportRowId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("SisImportRow");
                });

            modelBuilder.Entity("EAMS.Domain.Student", b =>
                {
                    b.HasOne("EAMS.Domain.School", "School")
                        .WithMany("Students")
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("EAMS.Domain.StudentGroup", b =>
                {
                    b.HasOne("EAMS.Domain.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EAMS.Domain.Term", "Term")
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("School");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("EAMS.Domain.StudentGroupMember", b =>
                {
                    b.HasOne("EAMS.Domain.StudentGroup", "StudentGroup")
                        .WithMany("Members")
                        .HasForeignKey("StudentGroupId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EAMS.Domain.Student", "Student")
                        .WithMany()
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Student");

                    b.Navigation("StudentGroup");
                });

            modelBuilder.Entity("EAMS.Domain.StudentTermRecord", b =>
                {
                    b.HasOne("EAMS.Domain.College", "College")
                        .WithMany()
                        .HasForeignKey("CollegeId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EAMS.Domain.AcademicProgram", "Program")
                        .WithMany()
                        .HasForeignKey("ProgramId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("EAMS.Domain.Student", "Student")
                        .WithMany("TermRecords")
                        .HasForeignKey("StudentId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EAMS.Domain.Term", "Term")
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("College");

                    b.Navigation("Program");

                    b.Navigation("Student");

                    b.Navigation("Term");
                });

            modelBuilder.Entity("EAMS.Domain.SystemSetting", b =>
                {
                    b.HasOne("EAMS.Domain.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("School");
                });

            modelBuilder.Entity("EAMS.Domain.Term", b =>
                {
                    b.HasOne("EAMS.Domain.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("EAMS.Domain.User", b =>
                {
                    b.HasOne("EAMS.Domain.School", "School")
                        .WithMany()
                        .HasForeignKey("SchoolId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("School");
                });

            modelBuilder.Entity("EAMS.Domain.UserRole", b =>
                {
                    b.HasOne("EAMS.Domain.Role", "Role")
                        .WithMany("UserRoles")
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("EAMS.Domain.User", "User")
                        .WithMany("UserRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Role");

                    b.Navigation("User");
                });

            modelBuilder.Entity("EAMS.Domain.College", b =>
                {
                    b.Navigation("Programs");
                });

            modelBuilder.Entity("EAMS.Domain.Course", b =>
                {
                    b.Navigation("Offerings");
                });

            modelBuilder.Entity("EAMS.Domain.CourseOffering", b =>
                {
                    b.Navigation("Enrollments");

                    b.Navigation("Instructors");
                });

            modelBuilder.Entity("EAMS.Domain.Event", b =>
                {
                    b.Navigation("AttendanceRecords");

                    b.Navigation("Schedules");
                });

            modelBuilder.Entity("EAMS.Domain.Permission", b =>
                {
                    b.Navigation("RolePermissions");
                });

            modelBuilder.Entity("EAMS.Domain.Role", b =>
                {
                    b.Navigation("RolePermissions");

                    b.Navigation("UserRoles");
                });

            modelBuilder.Entity("EAMS.Domain.School", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("Students");
                });

            modelBuilder.Entity("EAMS.Domain.SisImportBatch", b =>
                {
                    b.Navigation("Rows");
                });

            modelBuilder.Entity("EAMS.Domain.SisImportProfile", b =>
                {
                    b.Navigation("Columns");
                });

            modelBuilder.Entity("EAMS.Domain.SisImportRow", b =>
                {
                    b.Navigation("Entities");
                });

            modelBuilder.Entity("EAMS.Domain.Student", b =>
                {
                    b.Navigation("Cards");

                    b.Navigation("Enrollments");

                    b.Navigation("TermRecords");
                });

            modelBuilder.Entity("EAMS.Domain.StudentGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("EAMS.Domain.User", b =>
                {
                    b.Navigation("UserRoles");
                });
#pragma warning restore 612, 618
        }
    }
}
